apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: classifier-api
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: classifier-api
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
    - type: Pods
      pods:
        metric:
          name: get_latency
        target:
          type: AverageValue
          averageValue: 1
