apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter-config
  namespace: default
data:
  config.yaml: |
    prometheus:
      url: http://192.168.49.2:31223
    rules:
      default: false
      custom:
      - seriesQuery: 'get_latency_count'
        resources:
          overrides:
            namespace: {resource: "namespace"}
            pod: {resource: "pod"}
        name:
          matches: "^(.*)_count"
          as: "${1}"
        metricsQuery: 'sum(rate(<<.Series>>[5m])) by (<<.GroupBy>>) * 100'

