apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-metrics-config
  namespace: default
data:
  config.yaml: |
    rules:
      - seriesQuery: 'get_latency_sum'
        resources:
          overrides:
            namespace:
              resource: namespace
            pod:
              resource: pod
        name:
          matches: ""
          as: "get_latency"
        metricsQuery: 'get_latency_sum'

